### ISSUE TITLE
Updating from game always fails (BLT 2.0)

### ISSUE THREAD

**Issue by ElReyZero1201** [JamesWilko/Payday-2-BLT#90] opened 2017-08-31 23:19 UTC
everytime i try to update from game it says failed to update with the new BLT

**Comment by TheOfficialJosh** [comment] 2017-09-01 02:35
Confirmed, and I can't get it to retry, even though it suggests it.

**Comment by Alcat101** [comment] 2017-09-01 08:06
Manually update the BLT.

Download BLT 2.0, then copy-paste-replace the files into Payday 2 dir

**Comment by JamesWilko** [comment] 2017-09-01 08:06
What mods are you trying to update?

**Comment by Omen267901** [comment] 2017-09-01 11:55
Same here. All mods are failing to update, and beardlib mods are crashing the game if I try to update them (already reported on beardlib page, just adding it here).

**Comment by ianlee0800** [comment] 2017-09-01 13:05
Same here, none of my mod updates successfully.
For example: Iter, Keepers, Full Speed Swarm, Custom Waypoint

**Comment by Slunkee** [comment] 2017-09-01 16:39
Same here.

**Comment by xlis1** [comment] 2017-09-02 03:44
happening to me too. when i click update on any mods it downloads extracts and fails. console log: (had to use dropbox as it was too long for pastebin ;-;) https://www.dropbox.com/s/w3d79u5vtwlzkl2/2017_09_01_log.txt?dl=0

**Comment by b33croft1992** [comment] 2017-09-02 06:56
same for me too beardlib failed try again

**Comment by chromKa** [comment] 2017-09-02 06:57
same too

**Comment by Alcat101** [comment] 2017-09-02 08:48
This is a known issue of BLT 2.0
Update mods manually, and ignore BLT auto-udpate system for now.

**Comment by Luffyyy** [comment] 2017-09-03 19:15
I don't really know if I'm correct on this but: BLT seems to compare hash of extracted zip file to the server one which is a zip file? I'm sure we cannot upload folders + it would be inefficient af.
*this happens when it's about to install the update.

**Comment by xlis1** [comment] 2017-09-03 20:27
assuming luffyyy is right and its comparing the extracted md5 hash to the zips hash then its no wonder it fails. if this is the case than you can fix it by checking the md5 hash before you extract. or store the md5 hash of the mod in the zip itself and check against that.

**Comment by Luffyyy** [comment] 2017-09-03 23:02
It's SHA256.
so one thing we know is that as of now BLT itself has no issue and the hash is equal to the server, I don't know if this was made forcibly or they actually have it working but using either winrar or 7zip to archive the mod into a zip file[ps: it could super cool if unzip supported not only zip ;)] both generate a completely wrong hash in the server causing the said issue.
So @JamesWilko how exactly did you archive BLT to make it work?

**Comment by ghost** [comment] 2017-09-04 00:40
Same. At least all my currently existing mods still work though.

**Comment by JamesWilko** [comment] 2017-09-04 11:50
Archives themselves are not hashed, the contents of the archive is extracted and hashed to check that. Should be fixed up from some commits made to the Lua repo https://github.com/JamesWilko/Payday-2-BLT-Lua/commits/master.

**Comment by SirWaddles** [comment] 2017-09-06 05:50
The hashes should be the same even if you check from a different directory, so long as the contents of the files are unchanged. I tested this functionality, it uses alphabetical order on the filenames in order to do the concatenation but the filepaths themselves are not part of the hash.

**Comment by BangL** [comment] 2017-09-06 06:12
this is actually already fixed.

the problem was that one parent folder for all mods got hashed. works if
only downloading one mod per time, and the folder keeps clean. but when
downloading more than one.. boom.. hash-salad.

**Comment by JamesWilko** [comment] 2017-09-19 13:15
This should have been fixed in BLT 2.2.

**Closed by JamesWilko** 2017-09-19 13:15 UTC
