### ISSUE TITLE
Can't access mod options / update existing mods

### ISSUE THREAD

**Issue by rcmero** [JamesWilko/Payday-2-BLT#100] opened 2017-09-01 14:10 UTC
First off, I want to thank you for patching this so quickly. I was worried that I'd have to get rid of all my mods but most of them are still operational, and the ones that didn't work just didn't load. I just had the game crash on me once, and that was from a mod that had already crashed the game from a previous update (pretty sure I disabled that...).

I did notice on a couple of issues once I've installed this update, which I am reporting now.

1. The BLT is not extracting the mods after updating, I see them in the downloads folder and I can update them manually, but the BLT is not updating them automatically.
![20170901112957_2](https://user-images.githubusercontent.com/5708421/29973408-54ae4f54-8f27-11e7-9521-735d5e183763.jpg)

2. I can't access the options for my existing mods. I'm not sure if this issue is from the BLT or one of the mods I have installed.
![20170901113013_1](https://user-images.githubusercontent.com/5708421/29973450-7da269c2-8f27-11e7-9c19-123a61c3abb9.jpg)

**Comment by BangL** [comment] 2017-09-01 14:33
and another duplicate of #95. nice screenshots though.
can you also provide a log file that shows the messages during the failed update process?
pastebin.com is a good site to upload logs

**Comment by BangL** [comment] 2017-09-01 14:37
ugh.. i meant duplicate of #90, not 95 ... my bad

**Comment by chromKa** [comment] 2017-09-01 15:45
+ same too

**Comment by rcmero** [comment] 2017-09-02 20:21
I find the logs in the mods folder, correct? Because after the latest
update the game starts a console window in the background, not sure if the
BLT is doing this.

(Also, I checked that the BLT is attempting to extract the mods to their
correct folder, as I see a _temp folder on the mods folder.)

Em 01/09/2017 15:33, "BangL" <notifications@github.com> escreveu:

**Comment by BangL** [comment] 2017-09-02 20:27
i dont need logs anymore, found out what the problem is. working on it.

**Comment by JamesWilko** [comment] 2017-09-19 13:15
This should have been fixed in BLT 2.2.

**Closed by JamesWilko** 2017-09-19 13:15 UTC
