### ISSUE TITLE
As of the latest update (u91), BLT won't allow Vehicle Controls to be rebound

### ISSUE THREAD

**Issue by karasuhebi** [JamesWilko/Payday-2-BLT#41] opened 2015-12-04 03:35 UTC
As of the latest update, OVERKILL has added in the ability to have a separate set of keys for when you're in a vehicle, and by design, the "In Vehicle" keys are allowed to be the same as the "On Foot" ones, and indeed some of them overlap the "On Foot" keys by default. BLT won't let you rebind any of these actions to keys already being used. This is an issue if for example the user is left-handed and use the arrow keys on foot, they can't set their arrow keys for the "In Vehicle" movement because of BLT.

It also has this weird bug (which I think it's had for a while but has become much more obvious now) where when you click on an action to set a key to it, it reads your mouse click as the key you're trying to set to that action, so you are forced to navigate with your keyboard and press Enter to activate the key binding process.

**Comment by Malidictus** [comment] 2015-12-06 01:12
I'm suffering the same problem. It seems like with BLT active, attempts to edit keys (any keys, be they on foot or in a vehicle) result in the game attempting to bind the key to left mouse or enter, depending on what you used to attempt to change the key. With BLT disabled, key rebinding works fine.

**Comment by JamesWilko** [comment] 2015-12-06 02:56
Key binding in the base game was changed in Update 91, the changes have been merged and should work as intended now.

**Closed by JamesWilko** 2015-12-06 02:56 UTC
