### ISSUE TITLE
does not open the game

### ISSUE THREAD

**Issue by reikasha** [JamesWilko/Payday-2-BLT#88] opened 2017-08-31 19:05 UTC
since they updated the game and update the bolt 2.0 does not open the game I just stay in running please update it :(

**Comment by tom-GER** [comment] 2017-08-31 19:20
Are you using the newest version?

**Comment by Vlad-00003** [comment] 2017-08-31 19:20
Same issue here.
So, a bit description of my situation - I've reinstall the game, so it's fresh. The game starts fine and works like it should.
Then I'm trying to put latest BLT there. Just copy IPHLPAPI.dll and mods folder to the game root, like I did yesterday and it us to work.
And that's it. The game doesn't even start. It just runs on 1535 kb of memory and do nothing else.
I've tried to delete mods folder, and the same happened. If IPHLPAPI.dll is in the root directory of the game - it doesn't start.
Also - there is no crash log or something - the game isn't crashing. It just wont start... O_o
Any ideas?
%appdata%\..\local\PAYDAY 2 is empty.

**Comment by Vlad-00003** [comment] 2017-08-31 19:20
Newest version of BLT, clean game.

**Comment by knzchaos** [comment] 2017-08-31 19:30
I have the same issue as Vlad-00003, game runs as a kind of "background process" until I delete IPHLPAPI.dll, I even deleted my old "mods" folder and still can't get the game to work with BLT.

**Comment by reikasha** [comment] 2017-08-31 19:55
I tried it but it does not work the same I will wait for a new update :+1:

**Comment by reikasha** [comment] 2017-08-31 19:59
not same as install or Reinstalling same does not open the game

**Comment by xGalaxy97x** [comment] 2017-08-31 21:59
Same happening to me: PD2 doesn't start...

**Comment by victorn1992** [comment] 2017-09-01 03:45
I am having the same issue.

1)  Removed all mods from the payday 2/mods folder
2)  Deleted mods folder, mods_overwrite folder, and IPHLPAPI.dll
3)  Installed fresh install of BLT 2.0

When i start payday2 the game loads as a process but never loads to the game.  When I remove the IPHLPAPI.dll then the game loads normally.  I tried the IPHLPAPI.dll included in the source code for BLT 2.0 and the game loaded normally, but there were no menu options (implying that BLT was not loading).  The IPHLPAPI.dll included in the BLT 2.0 compiled release and the IPHLPAPI.dll in the source code have a different file size, so I am guessing the one in the source code could be the old .dll  

I am running windows 7, VC redist x86 12.0.30501 (along with many others)

I tried to delete VC distros and reinstall and that did not help.  I have this feeling it is something to do with cURL and the .dll being built for win 10?  I am probably a 1/10 with programming skills, so I really am just guessing.  

Thanks for any help!

**Comment by BangL** [comment] 2017-09-01 09:05
all people with this issue seem to have one thing in common: Win7 instead of 10. can you confirm that?

**Comment by Vlad-00003** [comment] 2017-09-01 09:06
BangL, As i said in another issue(is there any way to combine them all in one?) 
I'm running Win7.
victorn1992 is running win7.

**Comment by Vlad-00003** [comment] 2017-09-01 09:09
![image](https://user-images.githubusercontent.com/31519848/29963122-685720ee-8f0e-11e7-99ca-855d16dafdff.png)
Here is the image of how it looks like. And nothing changes over time.

**Comment by Patriot99** [comment] 2017-09-01 09:17
The same problem.

**Comment by Vlad-00003** [comment] 2017-09-01 09:19
Patriot99, What OS you are running? WIn 7?

**Comment by Scorpion2606** [comment] 2017-09-01 09:20
same issue with mine.. works without blt but no response as soon as i put blt without any other mod in it..  running win7

**Comment by Patriot99** [comment] 2017-09-01 09:29
I'm using Windows 10
I downloaded changed BLT and crashed.
I deleted the mods folder and the IPHLPAPI.dll file
I downloaded the new BLT and uploaded some of my favorite mods. The game runs at the command prompt and after that game, but the game has crashed right after the game intro, but during intra game you can minimize the game and see in the command line how the mods load, but always at some jumps red errors lol
A similar problem, but the game also does not work.
He's trying to overhaul the game and rewrite everything.

**Comment by BangL** [comment] 2017-09-01 09:37
@Patriot99
1. maybe dont expect mods to run properly, which are obviously out of date
2. maybe dont post a completely different issue seperately, your issue is not related to this discussion
3. maybe provide log/crash files, if you expect someone to understand whats happening

**Comment by SilentAvenger12** [comment] 2017-09-01 09:45
im having the same problem totally fresh and clean payday 2 install (regrettably as it took 6 hours to reinstall) with only BLT added and its hanging on start up task manager and steam shows its running but wont actually start up, an i can confirm im on Win 7 Enterprise 64x

**Comment by JamesWilko** [comment] 2017-09-01 09:47
Thanks everyone, seems to be a Windows 7 issue, so I'm looking at getting it sorted.

**Comment by Vlad-00003** [comment] 2017-09-01 16:17
@JamesWilko, @BangL - any progress on making BLT work on Windows 7?
If you need a tester - I'll be happy to assist!

**Comment by Patriot99** [comment] 2017-09-01 16:38
@BangL 
1. Where did I mention that my mods are outdated?
2. I wrote under the topic '' does not open the game ''. I described my problem because it is similar and I came across it on the internet. I do not want to create a new topic and clutter with similar questions as to how to do 1 topic.
3. Problem solved.

**Comment by Vlad-00003** [comment] 2017-09-01 16:40
@Patriot99 Your problem isn't simular with this thread. Your game just crashes. Ours - doesn't even launch =)

**Comment by BangL** [comment] 2017-09-01 16:42
@Patriot99 " and uploaded some of my favorite mods ... but the game has crashed right after the game intro" <- there did you mention inderectly that your mods are outdated.
of course is your problem solved, cause you updated/cleaned your broken mods, :)

**Comment by Patriot99** [comment] 2017-09-01 16:43
@Vlad-00003
 I also had a problem, but the post I wrote already how can I open the game.
But the problem has already resolved so there is no problem to continue.

**Comment by Vlad-00003** [comment] 2017-09-01 16:44
@BangL, so what? Any ideas why the BLT doesn't work on Windows 7? I really can't play the game without my favorite mods. I'm able to make them work on the newer version myself, If it'll be working on my PC.
I really don't wanna update to Win 10, cos I hate the UI =(

**Comment by BangL** [comment] 2017-09-01 16:48
no idea, but im sure wilko will find a way to fix it. just be patient.

On 1 Sep 2017 18:44, "Vlad-00003" <notifications@github.com> wrote:

@BangL <https://github.com/bangl>, so what? Any ideas why the BLT doesn't
work on Windows 7? I really can't play the game without my favorite mods.
I'm able to make them work on the newer version myself, If it'll be working
on my PC.
I really don't wanna update to Win 10, cos I hate the UI =(

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/JamesWilko/Payday-2-BLT/issues/88#issuecomment-326629091>,
or mute the thread

**Comment by Patriot99** [comment] 2017-09-01 16:50
@BangL 
Maybe I wrote this wrong, but I was more concerned that I uploaded my mods to BLT and crashed after launch.
All mods are up-to-date because I'm checking to see if they are up to date.
Often as something happens it's worth downloading again the BLT, but that did not work.
In this case, I downloaded a new game, I added a new BLT and added my mods again.

**Comment by AdnanLord** [comment] 2017-09-02 08:09
@Vlad-00003 Same problem with me and i am using WIN 7 Ultimate 64x any fix at the moment ?? :(((

**Comment by reikasha** [comment] 2017-09-02 10:09
I already did it work but the only problem is that if or if you have to have windows 10  :(

**Comment by JamesWilko** [comment] 2017-09-19 13:38
Issue was fixed with release of BLT 2.1.

**Closed by JamesWilko** 2017-09-19 13:38 UTC
