### ISSUE TITLE
Game does not open up but Task Manager shows payday2_win32_release.exe as currently running [BLT2_release_r6_r16]

### ISSUE THREAD

**Issue by AmperAndSand** [JamesWilko/Payday-2-BLT#95] opened 2017-09-01 06:54 UTC
I've removed the entire 'mods' folder (including `mods\saves\` within it) and the old IPHLPAPI.dll in `\Steam\steamapps\common\PAYDAY 2\` before installing the latest release from https://github.com/JamesWilko/Payday-2-BLT/releases (BLT2_release_r6_r16.zip).
 
The game does not start at all. Task Manager says payday2_win32_release.exe is currently running and taking up 0% CPU resources, but the game does not open up. Steam also shows that PAYDAY 2 is running.

EDIT: 
OS: Windows 7 64-bit. 
No antivirus installed.

**Comment by JamesWilko** [comment] 2017-09-01 08:39
What OS are you using, and what anti-virus do you have installed?

**Comment by BangL** [comment] 2017-09-01 09:03
all people with this issue seem to have one thing in common: Win7 instead of 10. can you confirm that?

**Comment by Vlad-00003** [comment] 2017-09-01 09:03
JamesWilko, I have the same problem. Windows 7, no anti-virus at all.

**Comment by Vlad-00003** [comment] 2017-09-01 09:04
Bangl, I can't confirm that, but my OS is win7, and I have this issue.

**Comment by Scorpion2606** [comment] 2017-09-01 09:32
same issue with win7

**Comment by AmperAndSand** [comment] 2017-09-01 09:36
Windows 7, 64-bit. No antivirus installed.

**Comment by AkiraDaishiyuExe** [comment] 2017-09-01 09:39
Yes we can confirmed, same issue, Win7

**Comment by JamesWilko** [comment] 2017-09-01 09:47
Thanks everyone, seems to be a Windows 7 issue, so I'm looking at getting it sorted.

**Comment by Vlad-00003** [comment] 2017-09-01 09:48
Thanks James, Thanks BangL! Will be waiting for the update on this!

**Comment by AkiraDaishiyuExe** [comment] 2017-09-01 09:50
Glad we helped c:

**Comment by gobbo1008** [comment] 2017-09-01 09:50
Happy to provide testing if needed, running Win7 Ultimate x64.

**Comment by AkiraDaishiyuExe** [comment] 2017-09-01 09:52
Me too

**Comment by SilentAvenger12** [comment] 2017-09-01 09:56
thank you almighty BLT jesus may the code gods guide you in your quest to fix this issue and bless you with busty thicc women all your life BLT jesus

**Comment by TangleNathair** [comment] 2017-09-01 13:56
Same exact issue, W7 Ultimate x64, no AV, all as above.

**Comment by saladofstones** [comment] 2017-09-02 01:33
Can confirm that it doesn't work. Feel sad that its been so long without a fix. Best of luck

**Comment by dive-bomber** [comment] 2017-09-02 12:22
https://github.com/JamesWilko/Payday-2-BLT/issues/110

Has anybody shown this to James?

**Comment by AmperAndSand** [comment] 2017-09-03 10:49
This issue seems to have been fixed as of v2.1. Just tried it on Windows 7.

**Comment by JamesWilko** [comment] 2017-09-04 11:48
Fixed in BLT 2.1 update.

**Closed by JamesWilko** 2017-09-04 11:48 UTC
