### ISSUE TITLE
Crashing after start a heist

### ISSUE THREAD

**Issue by renaki4** [JamesWilko/Payday-2-BLT#167] opened 2017-10-28 18:04 UTC
I updated BLT a few days ago and after that whenever I start a heist payday crashes.

```
Application has crashed: C++ exception
mods/WolfHUD/lua/GameInfoManager.lua:3691: attempt to call method '_total_armor' (a nil value)



SCRIPT STACK

set_armor_original() @mods/WolfHUD/lua/GameInfoManager.lua:3689
set_armor() @mods/WolfHUD/lua/GameInfoManager.lua:3689
_regenerate_armor() lib/units/beings/player/playerdamage.lua:533
replenish() lib/units/beings/player/playerdamage.lua:519
init_original() lib/units/beings/player/playerdamage.lua:33
init_original() @mods/WolfHUD/lua/GameInfoManager.lua:3562
init_original() @mods/WolfHUD/lua/GameInfoManager.lua:3562
@mods/WolfHUD/lua/GameInfoManager.lua:3562
spawn_unit() =[C]
spawn_unit() lib/network/base/networkpeer.lua:2126
spawn_players() lib/network/base/basenetworksession.lua:1498
update_original() lib/states/ingamewaitingforplayers.lua:262
update() @mods/WolfHUD/lua/MenuTweaks.lua:588
update() core/lib/utils/game_state_machine/coregamestatemachine.lua:92
update() lib/setups/setup.lua:790
update() lib/setups/gamesetup.lua:654
update() lib/setups/networkgamesetup.lua:21
core/lib/setups/coresetup.lua:537


-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name                                        


-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.80.413.
	CPU : Intel(R) Core(TM) i5-4430 CPU @ 3.00GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 650 Ti / nvldumd.dll[22.21.13.8494]
	Language : english
	Memory :     16263MB 12KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Microsoft (Alto-falantes (TRITTON 720+ Headset))
```

**Comment by PJzuza** [comment] 2017-10-29 14:04
Duplicate of #164

**Closed as completed** 2017-10-29 23:42 UTC
